// GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Run `npm run gen-version` (also runs on `prebuild`). its own suite
// pins the emitted User-Agent to package.json.version, so a stale copy fails the suite.
export const VERSION = "0.2.1"
